services:
  type-juggling-lab:
    container_name:  type-juggling-lab
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5013:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    depends_on:
      -  type-juggling-db
  
  type-juggling-db:
    container_name:  type-juggling-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: administracion
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql