services:
  # sqli-db:
  #   container_name: sqli-db
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: tienda
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./sqli-lab/init.sql:/docker-entrypoint-initdb.d/init.sql

  # sqli-lab:
  #   container_name: sqli-lab
  #   build:
  #     context: ./sqli-lab
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - sqli-db
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FLASK_ENV=development
  #   command: ["python", "app.py"]
  
  # ssti-lab:
  #   container_name: ssti-lab
  #   build:
  #     context: ./ssti-lab
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5001:5000"
  #   environment:
  #     - FLASK_ENV=development
  #   command: ["python", "app.py"]
  # lfi-lab:
  #   container_name: lfi-lab
  #   build:
  #     context: ./lfi-lab
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5002:80"
  #   environment:
  #     - APACHE_DOCUMENT_ROOT=/var/www/html

  # xxe-lab:
  #   container_name: xxe-lab
  #   build:
  #     context: ./xxe-lab
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5003:5000"
  #   environment:
  #     - FLASK_ENV=development
  #   command: ["python", "app.py"]

  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./nosqli-lab/init.js:/docker-entrypoint-initdb.d/init.js
  
  # nosqli-lab:
  #   container_name: nosqli-lab
  #   restart: always
  #   build:
  #     context: ./nosqli-lab
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "5004:3000"

  # rfi-lab:
  #   container_name: rfi-lab
  #   build:
  #     context: ./rfi-lab
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5005:80"
  #   environment:
  #     - APACHE_DOCUMENT_ROOT=/var/www/html

  # deserialization-lab:
  #   container_name: deserialization-lab
  #   build:
  #     context: ./deserialization-lab
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5006:5000"
  #   environment:
  #     - FLASK_ENV=development
  #   command: ["python", "app.py"]

  ssrf-lab:
    container_name: ssrf-lab
    build:
      context: ./ssrf-lab/web_server
      dockerfile: Dockerfile
    ports:
      - "5007:5000"
    privileged: true
    depends_on:
      - ssrf-api
    networks:
      - ssrf_network
    environment:
      - FLASK_ENV=development
    
  ssrf-api:
    container_name: ssrf-api
    build:
      context: ./ssrf-lab/api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - ssrf_network

networks:
  ssrf_network:

  # log-poisoning-lab:
  #   container_name: log-poisoning-lab
  #   build:
  #     context: ./log-poisoning-lab
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5008:80"
  #     - "2222:22"
  #   environment:
  #     - APACHE_DOCUMENT_ROOT=/var/www/html
  

