services:
  # sqli-db:
  #   container_name: sqli-db
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: tienda
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # sqli-lab:
  #   container_name: sqli-lab
  #   build:
  #     context: ./sqli-lab
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - sqli-db
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FLASK_ENV=development
  #   command: ["python", "app.py"]
  
  ssti-lab:
    container_name: ssti-lab
    build:
      context: ./ssti-lab
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    command: ["python", "app.py"]

