services:
  ssti-lab:
    container_name: ssti-lab
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    command: ["python", "app.py"]