services:
  ssrf-lab:
    container_name: ssrf-lab
    build:
      context: ./web_server
      dockerfile: Dockerfile
    ports:
      - "5007:5000"
    privileged: true
    depends_on:
      - ssrf-api
    networks:
      - ssrf_network
    environment:
      - FLASK_ENV=development
    
  ssrf-api:
    container_name: ssrf-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - ssrf_network

networks:
  ssrf_network: