services:
  deserialization-lab:
    container_name: deserialization-lab
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5006:5000"
    environment:
      - FLASK_ENV=development
    command: ["python", "app.py"]