services:
  xxe-lab:
    container_name: xxe-lab
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    environment:
      - FLASK_ENV=development
    command: ["python", "app.py"]