services:
  file-upload-lab:
    container_name: file-upload-lab
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5011:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    depends_on:
      - file-upload-db
  
  file-upload-db:
    container_name: file-upload-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social_network
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql